# Generated by Django 4.1.7 on 2023-03-24 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/questions/images')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.question')),
            ],
            options={
                'ordering': ['question'],
            },
        ),
    ]
