# Generated by Django 4.1.7 on 2023-03-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_questionimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionImages',
            new_name='QuestionImage',
        ),
    ]
