# Generated by Django 4.1.7 on 2023-03-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_rename_questionimages_questionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='QImage', to='vote.questionimage'),
        ),
    ]
