# Generated by Django 4.1.7 on 2023-03-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_question_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='images',
        ),
    ]
