# Generated by Django 4.1.7 on 2023-03-24 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_alter_questionimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_age',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vote.agerange'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_zip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vote.zipcode'),
            preserve_default=False,
        ),
    ]
