# Generated by Django 4.1.7 on 2023-03-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_vote_vote_age_vote_vote_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_zip',
            field=models.CharField(max_length=5),
        ),
    ]
